// export interface FileIndex {
//   [key: string]: any;
// }

export const images = {
  'milestones': require('./images/home-milestones.jpg'),
  'infant-massage': require('./images/infant-massage.jpg'),
  'services': require('./images/services.jpg'),
  'method': require('./images/the-method.jpg'),
  'about-me': require('./images/about-me.jpg'),
  'pre-birth': require('./images/pre-birth.jpg'),
  'pre-birth-bw': require('./images/pre-birth-bw.jpg'),
  'welcome': require('./images/welcome.jpg'),
  'welcome-bw': require('./images/welcome-bw.jpg'),
  'rolling': require('./images/rolling.jpg'),
  'rolling-bw': require('./images/rolling-bw.jpg'),
  'army-crawl': require('./images/army-crawl.jpg'),
  'army-crawl-bw': require('./images/army-crawl-bw.jpg'),
  'crawling': require('./images/crawling.jpg'),
  'crawling-bw': require('./images/crawling-bw.jpg'),
  'sitting-independently': require('./images/sitting-independently.jpg'),
  'sitting-independently-bw': require('./images/sitting-independently-bw.jpg'),
  'standing': require('./images/standing.jpg'),
  'standing-bw': require('./images/standing-bw.jpg'),
  'walking-independently': require('./images/walking-independently.jpg'),
  'walking-independently-bw': require('./images/walking-independently-bw.jpg'),
  'services-header': require('./images/services-header.jpg'),
  'milestones-header': require('./images/milestones-header.jpg'),
  'challenge': require('./images/challenge.jpg'),
  'holistic': require('./images/holistic.jpg'),
  'testimonials-1': require('./images/testimonials-1.jpg'),
  'testimonials-2': require('./images/testimonials-2.jpg'),
  'testimonials-3': require('./images/testimonials-3.jpg'),
  'testimonials-4': require('./images/testimonials-4.jpg'),
}
